apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubbles-frontend
  namespace: openshift-gitops # change to argocd if using minikube
spec:
  destination:
    namespace: bubbles-argorollouts
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: bubbles-frontend/src/main/argorollouts
    repoURL: https://github.com/redhat-developer-demos/bubbles-progressive-delivery.git
    targetRevision: quarkus3
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true