apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bubbles-argorollouts

resources:
- rollout-analysis.yaml
- analysistemplate.yaml
- Service-canary.yaml
- Service.yaml
- virtual-service-bubble-backend-v1_and_v2_100_0.yaml

patchesStrategicMerge:
  - | 
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: bubblebackend
    spec:
      template:
        spec:
          containers:
          - name: bubblebackend 
            env:
            - name: BUBBLE_COLOR
              value: red