apiVersion: v1
kind: Service
metadata:
  name: bubble-backend
  labels:
    app: bubblebackend
  annotations:
    argocd.argoproj.io/sync-wave: "1"    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: bubblebackend
