---
apiVersion: "v1"
kind: ServiceAccount
metadata:
  name: bubblefrontend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bubblefrontend-view
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: bubblefrontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["list", "get"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bubblefrontend
    version: v1
  name: bubblefrontend
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bubblefrontend
      version: v1
  template:
    metadata:
      labels:
        app: bubblefrontend
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: bubblefrontend
        image: quay.io/rhdevelopers/bubble-frontend:v1.0-istio
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        securityContext:
          privileged: false
      serviceAccount: bubblefrontend