apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bubble-backend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  hosts:
  - bubble-backend
  http:
  - route:
    - destination:
        host: bubble-backend
        subset: version-v1
      weight: 100
    - destination:
        host: bubble-backend
        subset: version-v2
      weight: 0