---
apiVersion: "v1"
kind: ServiceAccount
metadata:
  name: bubblefrontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bubblefrontend-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: bubblefrontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["routes"]
    verbs: ["list", "get"]
---